### ISSUE TITLE
Does the one shot plot need the error limits?

### ISSUE THREAD

**Issue by jeanconn** [sot/attitude_error_mon#1]

**Comment by taldcroft** [comment]
What is meant by "error limits" here?

**Comment by jeanconn** [comment]
Max error estimate?  I was thinking about the steps-lines on the similar
plot that I've seen from Bill.

**Comment by taldcroft** [comment]
Probably useful if not too much of a hassle.  But not a huge priority either.

**Comment by jeanconn** [comment]
I don't think we have the code handy to do the estimates (for starcheck we
have a rough formula but override with whatever we get in ManErr.txt,
right?).   Wasn't there some discussion of improving the estimates too?​
