### ISSUE TITLE
Missing big one-shots

### ISSUE THREAD

**Issue by taldcroft** [sot/attitude_error_mon#10]
Neither of the two very big one-shots recently are in the plot or data file, and there don't appear to be any one-shots in the plot > 90 arcsec (even though two of those are in the data file).  My guess this has to do with selecting first on dwells and then finding the corresponding maneuver, which misses maneuvers without a dwell.

```
In [14]: manvrs = events.manvrs.filter('2017:065', one_shot__gt=90)

In [15]: manvrs
Out[15]: 
<Manvr: start=2017:069:15:21:16.923 dur=1886 n_dwell=1 template=normal>
<Manvr: start=2017:073:08:28:49.617 dur=2619 n_dwell=1 template=normal>
<Manvr: start=2017:073:21:18:53.544 dur=2850 n_dwell=1 template=normal>
<Manvr: start=2017:075:04:07:38.026 dur=1574 n_dwell=1 template=normal>

In [16]: [manvr.one_shot for manvr in manvrs]
Out[16]: [109.47447204589844, 141.429443359375, 160.7604522705078, 90.6341323852539]
```

**Comment by jeanconn** [comment]
I thought this was due to #8, but yes, was planning to generalize the tool
to include worst cases that are likely getting directly or indirectly
filtered.

**Comment by taldcroft** [comment]
Makes sense, but we do want to make sure the set of one-shots is complete.

**Comment by jeanconn** [comment]
I'm also confused by what the one shot is on a maneuver without a dwell.

**Comment by taldcroft** [comment]
Technically one can get a one-shot as soon as AOACASEQ goes to GUID, whereas you can't have a dwell without KALM.  I think for most practical purposes they are the same if dwells can be arbitrarily short.  Kadi does allow short dwells, though there is some logic to ignore a short dwell within 400 seconds of a previous dwell (normally from a monitor window).

**Comment by jeanconn** [comment]
Gotcha.  I was thinking of a dwell as NPNT not KALM, so good to be on the
same page there.
